Repository voxpupuli/vox-pupuli-tasks, pull requests merged in 2019-10, with the labels that each got.

#86 implement basic logging for RepoStatusworker
  .rubocop_todo.yml
  app/workers/repo_status_worker.rb
Labels: enhancement

#89 RepoStatusWorker: fix error handling
  app/workers/repo_status_worker.rb
Labels: bug

#90 maybe fix nil:NilClass erorr
  app/workers/repo_status_worker.rb
Labels: bug

#91 RepoStatusWorker: explicitly return `data` in check_metadatas
  app/workers/repo_status_worker.rb
Labels: bug

#94 fix duplicate labels
  app/models/pull_request.rb
Labels: bug

#96 update category description
  app/views/dashboard/_os.html.haml
Labels: frontend/ui
