Repository voxpupuli/vox-pupuli-tasks, pull requests merged in 2020-05, with the labels that each got.

#161 Only add a comment of PR is eligible
  app/models/pull_request.rb
Labels: bug

#144 Set a PR label / comment if CI passes/fails
  app/models/label.rb
  app/models/pull_request.rb
  config/locales/en.yml
Labels: backend/eventhandler, enhancement

#162 Save CI status as PR attribute
  app/models/pull_request.rb
  db/migrate/20200501212046_add_status_to_pull_requests.rb
  db/schema.rb
Labels: backend/eventhandler, backend/poll-engine, enhancement

#164 pull_request: fix migration for status attribute
  db/migrate/20200501212046_add_status_to_pull_requests.rb
Labels: bug

#163 pull_request: save draft state
  app/models/pull_request.rb
  db/migrate/20200502213446_add_draft_to_pull_requests.rb
  db/schema.rb
Labels: backend/eventhandler

#165 Cleanup eligible_for_comment attribute
  app/models/pull_request.rb
  db/migrate/20200502221146_add_default_to_eligible_for_comment_in_pull_requests_modell.rb
  db/schema.rb
Labels: optimization

#166 Rename eligible_for_{,merge}comment / Prevent duplicate CI comments
  app/models/pull_request.rb
  db/migrate/20200502221147_fix_column_name.rb
  db/migrate/20200502221148_add_eligible_for_ci_comment.rb
  db/schema.rb
Labels: backend/eventhandler, optimization

#168 document docker commands
  README.md
Labels: documentation

#167 CI check: log PR status if its unknown
  app/models/pull_request.rb
Labels: backend/eventhandler, optimization

#170 Ignore postres-data directory
  .dockerignore
  .gitignore
Labels: documentation

#174 Dont modify PRs in development mode
  .rubocop.yml
  .rubocop_todo.yml
  app/models/pull_request.rb
Labels: backend/eventhandler, backend/notifier, enhancement

#175 Fix incorrect status handling
  .rubocop.yml
  .rubocop_todo.yml
  app/lib/github_event.rb
  app/models/pull_request.rb
  app/workers/refresh_pull_request_worker.rb
  db/migrate/20200503192132_change_pull_request_status.rb
  db/schema.rb
Labels: backend/eventhandler, backend/notifier, backend/poll-engine, bug

#176 fix last status
  app/controllers/dashboard_controller.rb
  app/views/dashboard/show.html.haml
Labels: bug

#180 Mark Debian 8 as EOL / update documentation for new/EOL OS checks
  README.md
  config/voxpupuli.yml
Labels: documentation

#179 validate a PR after every PR update / prevent loops
  .rubocop_todo.yml
  app/models/pull_request.rb
Labels: bug

#182 fix validation
  app/models/pull_request.rb
Labels: bug

#185 document sidekiq cleanup
  README.md
Labels: documentation

#186 Fix CI-check conditions / fix label method return values
  .rubocop_todo.yml
  app/models/pull_request.rb
Labels: bug

#189 dont treat sawyer object like a hash
  .rubocop_todo.yml
  app/models/pull_request.rb
Labels: bug
