Repository voxpupuli/vox-pupuli-tasks, pull requests merged in 2020-04, with the labels that each got.

#132 Add Ubuntu 20.04 to supported OS list
  config/locales/en.yml
  config/voxpupuli.yml
Labels: enhancement

#136 fix travis implementation
  app/controllers/incoming_controller.rb
Labels: bug

#140 fix typo in inline comment
  app/models/pull_request.rb
Labels: bug

#142 Document method + fix typo
  app/models/pull_request.rb
Labels: bug

#145 fix comparsion
  app/workers/repo_status_worker.rb
Labels: bug

#150 Add `irb` to development gems
  Gemfile
  Gemfile.lock
Labels: bug

#158 Dont validate a queued PR twice
  app/models/pull_request.rb
  app/workers/update_mergeable.rb
Labels: backend/eventhandler, backend/poll-engine, bug
